#spring:
#  profiles:
#    active: dev  # Automatically picks application-dev.yml
#
#app:
#  base-url: http://localhost:8080/api
#
#---
#spring:
#  profiles: prod
#  redis:
#    host: localhost
#    port: 6379
#    password: redis@spring#api
#    timeout: 60000
#    client-type: lettuce
#
#app:
#  base-url: https://api.yourdomain.com
