/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JavaApi;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppApiApplicationTest {
    // @Test public void testAppHasAGreeting() {
    //     App classUnderTest = new App();
    //     assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    // }
}
